# Generated by Django 5.1.2 on 2024-10-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strasse", models.CharField(max_length=100)),
                ("hausnummer", models.CharField(max_length=10)),
                ("postleitzahl", models.CharField(max_length=10)),
                ("stadt", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kontoinhaber", models.CharField(max_length=200)),
                ("iban", models.CharField(max_length=34)),
                ("bic", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(max_length=100)),
                ("nachname", models.CharField(max_length=100)),
                ("geburtsdatum", models.DateField()),
                ("geburtsort", models.CharField(max_length=100)),
                ("nationalitaet", models.CharField(max_length=100)),
                (
                    "familienstand",
                    models.CharField(
                        choices=[
                            ("ledig", "Ledig"),
                            ("verheiratet", "Verheiratet"),
                            ("geschieden", "Geschieden"),
                            ("verwitwet", "Verwitwet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telefonnummer", models.CharField(max_length=30)),
                ("emailadresse", models.EmailField(max_length=100)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="polls.address",
                    ),
                ),
                (
                    "bank_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="polls.bankdetails",
                    ),
                ),
            ],
        ),
    ]
