# Generated by Django 5.1.2 on 2024-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_address_bankdetails_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="beruf",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="telefonnummer",
            field=models.CharField(max_length=20),
        ),
    ]
